### ISSUE TITLE
error registering in nushell 0.92.2

### ISSUE THREAD

**Issue by kurokirasama** [FMotalleb/nu_plugin_port_scan#2]
```nu
Error:   × Error getting signatures
   ╭─[source:1:1]
 1 │ register /home/kira/.cargo/bin/nu_plugin_port_scan
   · ────┬───
   ·     ╰── Plugin failed to decode: data did not match any variant of untagged enum PluginOutput
   ╰────
```

**Comment by FMotalleb** [comment]
Hi, did you have any issues updating the plugin from the GitHub source code?

By the way, the migration to version 0.92 takes some time, but this plugin should now be fixed.

**Comment by kurokirasama** [comment]
sorry, I didn't see this before.

Now nushell is in version 0.96.1, using the new `plugin add`, it gives this error:
```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: unknown variant `Error`, expected one of `Hello`, `Option`, `CallResponse`, `EngineCall`, `Data`, `End`, `Drop`, `Ack`
```

**Comment by FMotalleb** [comment]
currently updating my packages to new version, it will be done in an hour or so

**Comment by kurokirasama** [comment]
super!!!

Thanks!

On Fri, 26 Jul 2024 11:08:47 -0400, Motalleb Fallahnezhad
***@***.***> said:
> currently updating my packages to new version, it will be done in an hour or so
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/FMotalleb/nu_plugin_port_scan/issues/2#issuecomment-2252965293
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

--
Luis Gomez G.

Director de Escuela Ingenieria Estadistica
Departamento de Estadistica
Facultad de Ciencias
Universidad del Bio-Bio
Concepcion, Chile
https://bit.ly/3nWEwsD
---
Email sent from cmdg 1.05 on Ubuntu 24.04

Special characters and accents have been omitted for system compatibility

**Comment by FMotalleb** [comment]
should be fixed now

**Comment by kurokirasama** [comment]
up to cargo, or just the repo?

**Comment by FMotalleb** [comment]
I am facing a power outage and I don't have my cargo secrets on my laptop

**Comment by FMotalleb** [comment]
you can use `cargo install --git https://github.com/FMotalleb/nu_plugin_port_scan` too, without cloning the repo itself
