### ISSUE TITLE
error in nushell 0.97.2

### ISSUE THREAD

**Issue by kurokirasama** [FMotalleb/nu_plugin_port_scan#3]
Hey, I just updated nushell to 0.97.2 and the plugin to 1.2.3, but when doing `plugin add ~/.cargo/bin/nu_plugin_port_scan` i get this error:

```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `description`
```

**Comment by FMotalleb** [comment]
Hi. 97.2?  the latest version on cargo is [97.1](https://crates.io/crates/nu)
please run the `version` command and send the output

**Comment by kurokirasama** [comment]
Hi, I installed from source today, and that's the version 
​
​| version | major | minor | patch | branch | commit_hash                              | build_os     | build_target             | rust_version                        | rust_channel                    | cargo_version                       | build_time                 | build_rust_channel | allocator | features                                 | installed_plugins                                                                          |
| ------- | ----- | ----- | ----- | ------ | ---------------------------------------- | ------------ | ------------------------ | ----------------------------------- | ------------------------------- | ----------------------------------- | -------------------------- | ------------------ | --------- | ---------------------------------------- | ------------------------------------------------------------------------------------------ |
| 0.97.2  | 0     | 97    | 2     | main   | 39b0f3bdda781a8edf961bb6dc746033cff46988 | linux-x86_64 | x86_64-unknown-linux-gnu | rustc 1.78.0 (9b00956e5 2024-04-29) | 1.78.0-x86_64-unknown-linux-gnu | cargo 1.78.0 (54d8815d0 2024-03-26) | 2024-08-23 10:05:45 -04:00 | release            | mimalloc  | default, sqlite, system-clipboard, trash | custom_values 0.1.0, formats 0.97.2, gstat 0.97.2, inc 0.97.2, polars 0.97.2, query 0.97.2 |
​

**Comment by FMotalleb** [comment]
If you're using a custom-built version of Nushell from the source code, that's a different story. My plugins likely won't support those builds (at least not yet). The main reason is that I have a full-time job and limited time to maintain my repositories.

If you want to use Nushell from the source code, you'll need to modify the `Cargo.toml` file in the plugins. As far as I can tell, there's no `nu-protocol` or `nu-plugin` version 97.2 available on Cargo yet, so it gets a bit tricky.

You can try this:

```nu
open Cargo.toml | update dependencies.nu-plugin { path: "<nushell's source path>/crates/nu-plugin" } | update dependencies.nu-protocol { path: "<nushell's source path>/crates/nu-protocol", features: $in.dependencies.nu-protocol.features } | save Cargo.toml
```

Then, attempt to build the plugin (though I can't guarantee it will work).

**Comment by FMotalleb** [comment]
and as far as I can remember one of my plugins is using another nu crate you need to modify that one as well (it's not this repo I think it's the clipboard plugin)
